{{- if .Values.ingress.enabled -}}
{{- range .Values.ingress.tls }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ include "shared-helm-chart.fullname" $ }}-{{ .secretName }}"
  labels:
    {{- include "shared-helm-chart.labels" $ | nindent 4 }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end}}
spec:
  secretName: {{ .secretName }}
  issuerRef:
    name: {{ .issuerRef.name }}
    kind: {{ .issuerRef.kind }}
  dnsNames:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
---
{{- end }}
{{- end }}