{{- if .Values.persistence.enabled -}}
{{- range .Values.persistence.claims }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "shared-helm-chart.fullname" $ }}-{{ .name }}"
  labels:
    {{- include "shared-helm-chart.labels" $ | nindent 4 }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end}}
spec:
  accessModes:
    - {{ .accessMode }}
  resources:
    requests:
      storage: {{ .size }}
---
{{- end }}
{{- end }}