{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: Secret
metadata:
 name: {{ include "shared-helm-chart.serviceAccountName" . }}
 annotations:
   kubernetes.io/service-account.name: {{ include "shared-helm-chart.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end}}